import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :bumble_web_app, BumbleWebAppWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  http: [port: System.get_env("PORT") || 4000],
  server: true,
  check_origin: ["http://localhost:4000"]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: BumbleWebApp.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

config :bumble_web_app, MyApp.Repo,
  url: System.get_env("DATABASE_URL"),
  pool_size: 10

config :bumble_web_app, ecto_repos: [BumbleWebApp.Repo]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
